[colors]
very-dark-grayish-blue = "hsl(217, 19%, 35%)"
desaturated-dark-blue = "#677693"
grayish-blue = "hsl(212, 23%, 69%)"
light-grayish-blue = "hsl(210, 46%, 95%)"
primary = "{colors.very-dark-grayish-blue}"
base = "{colors.desaturated-dark-blue}"
base-low = "{colors.grayish-blue}"
background = "{colors.light-grayish-blue}"
background-card = "black"