[colors]
type = "color"

# Very Dark Grayish Blue: hsl(217, 19%, 35%)
# Desaturated Dark Blue: hsl(214, 17%, 51%)
# Grayish Blue: hsl(212, 23%, 69%)
# Light Grayish Blue: hsl(210, 46%, 95%)

base = "hsl(214, 17%, 51%)"
secondary = "hsl(212, 23%, 69%)"	
accent = "#fff"
base-light = "hsl(210, 46%, 95%)"
primary = "hsl(217, 19%, 35%)"

